### ISSUE TITLE
Plugin causes PhpStorm to crash

### ISSUE THREAD

**Issue by driesvints** [inxilpro/IntellijAlpine#16]
A JetBrains engineer helped me to debug an issue where PhpStorm crashed randomly. It appears to be caused by this plugin. Unfortunately the only info I have is the following log:

```
"JobScheduler FJ pool 5/11" prio=0 tid=0x0 nid=0x0 waiting on condition
     java.lang.Thread.State: WAITING
 on java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync@94f9706 owned by "JobScheduler FJ pool 1/11" Id=53
    at java.base@11.0.10/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.10/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
    at java.base@11.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:1009)
    at java.base@11.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1324)
    at java.base@11.0.10/java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:738)
    at com.intellij.openapi.util.FieldCache.get(FieldCache.java:32)
    at com.intellij.xml.impl.schema.ComplexTypeDescriptor.getAttributes(ComplexTypeDescriptor.java:214)
    at com.intellij.xml.impl.schema.XmlElementDescriptorImpl.getAttributesDescriptors(XmlElementDescriptorImpl.java:280)
    at com.intellij.xml.impl.schema.XmlElementDescriptorImpl.getAttribute(XmlElementDescriptorImpl.java:369)
    at com.intellij.xml.impl.schema.XmlElementDescriptorImpl.getAttributeDescriptorImpl(XmlElementDescriptorImpl.java:333)
    at com.intellij.xml.impl.schema.XmlElementDescriptorImpl.getAttributeDescriptor(XmlElementDescriptorImpl.java:364)
    at com.intellij.psi.impl.source.xml.XmlAttributeDelegate.getDescriptionImpl(XmlAttributeDelegate.java:68)
    at com.intellij.psi.impl.source.xml.XmlAttributeDelegate.lambda$getDescriptor$0(XmlAttributeDelegate.java:55)
    at com.intellij.psi.impl.source.xml.XmlAttributeDelegate$$Lambda$3692/0x0000000802237440.compute(Unknown Source)
    at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
    at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
    at com.intellij.util.CachedValueBase$$Lambda$1646/0x00000008014ff040.compute(Unknown Source)
    at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
    at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
    at com.intellij.util.CachedValueBase$$Lambda$1645/0x00000008014ffc40.compute(Unknown Source)
    at com.intellij.openapi.util.RecursionGuard$$Lambda$1260/0x0000000800fe6c40.compute(Unknown Source)
    at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
    at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
    at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
    at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
    at com.intellij.psi.impl.source.xml.XmlAttributeDelegate.getDescriptor(XmlAttributeDelegate.java:53)
    at com.intellij.psi.impl.source.xml.XmlAttributeImpl.getDescriptor(XmlAttributeImpl.java:191)
    at com.intellij.xml.util.XmlEnumeratedValueReferenceProvider.getDescriptor(XmlEnumeratedValueReferenceProvider.java:85)
    at com.intellij.xml.util.XmlEnumeratedValueReferenceProvider.getReferencesByElement(XmlEnumeratedValueReferenceProvider.java:63)
...
    at com.github.inxilpro.intellijalpine.AttributeUtil.getDefaultHtmlAttributes(AttributeUtil.kt:78)
    at com.github.inxilpro.intellijalpine.AttributeUtil.getValidAttributes(AttributeUtil.kt:45)
    at com.github.inxilpro.intellijalpine.Injector.isAlpineAttribute(Injector.kt:40)
    at com.github.inxilpro.intellijalpine.Injector.getLanguagesToInject(Injector.kt:22)
...
```

**Comment by inxilpro** [comment]
This should be resolved in [https://github.com/inxilpro/IntellijAlpine/releases/tag/v0.3.0](v0.3.0) — the official plugin is pending approval with JetBrains.
