### ISSUE TITLE
exception "Wasn't parsed as expression in null" on version 0.6.3 

### ISSUE THREAD

**Issue by richmondb** [inxilpro/IntellijAlpine#58]
Software/System Information
OS: Linux
Plugin Version : 0.6.3
PhpStorm 2023.3.2

Error Log 
--------------
Wasn't parsed as expression in null

java.lang.Throwable
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:130)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:388)
	at com.intellij.lang.javascript.psi.impl.JSChangeUtil.createExpressionFromText(JSChangeUtil.java:185)
	at com.intellij.lang.javascript.psi.impl.JSChangeUtil.createExpressionWithContext(JSChangeUtil.java:170)
	at com.intellij.lang.javascript.psi.JSInheritedLanguagesConfigurableProvider.createExpressionFromText(JSInheritedLanguagesConfigurableProvider.java:80)
	at com.intellij.lang.javascript.psi.JSInheritedLanguagesHelper.createExpressionFromText(JSInheritedLanguagesHelper.java:104)
	at com.github.inxilpro.intellijalpine.AlpineAttributeInjectionHeader.serialize(AlpineAttributeInjectionHeader.kt:43)
	at com.github.inxilpro.intellijalpine.AlpineJavaScriptAttributeValueInjector.addWithData(AlpineJavaScriptAttributeValueInjector.kt:246)
	at com.github.inxilpro.intellijalpine.AlpineJavaScriptAttributeValueInjector.getPrefixAndSuffix(AlpineJavaScriptAttributeValueInjector.kt:221)
	at com.github.inxilpro.intellijalpine.AlpineJavaScriptAttributeValueInjector.getLanguagesToInject(AlpineJavaScriptAttributeValueInjector.kt:147)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:495)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.probeElementsUpInner(InjectedLanguageUtilBase.java:234)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.lambda$probeElementsUp$0(InjectedLanguageUtilBase.java:214)
	at com.intellij.openapi.application.impl.ReadActionCacheImpl$allowInWriteAction$1.invoke(ReadActionCacheImpl.kt:41)
	at com.intellij.openapi.application.impl.ReadActionCacheImpl$allowInWriteAction$1.invoke(ReadActionCacheImpl.kt:41)
	at com.intellij.openapi.application.impl.ReadActionCacheImpl.allowInWriteAction(ReadActionCacheImpl.kt:29)
	at com.intellij.openapi.application.impl.ReadActionCacheImpl.allowInWriteAction(ReadActionCacheImpl.kt:41)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.probeElementsUp(InjectedLanguageUtilBase.java:213)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtilBase.enumerate(InjectedLanguageUtilBase.java:156)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.enumerateEx(InjectedLanguageManagerImpl.java:379)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.lambda$processInjectedPsiFiles$6(InjectedGeneralHighlightingPass.java:173)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:139)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:152)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:152)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:108)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:86)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:184)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:86)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by inxilpro** [comment]
I just submitted `v0.6.4` for review, which should address some performance issues. Please let me know if the issue persists after updating!
